### ISSUE TITLE
Data entry

### ISSUE THREAD

**Issue by JobNmadu** [AntoineSoetewey/statsandr#1]
Rather than use long hand to create the database, it is more productive to create a file that holds the data. In that way, it is easier to edit the database without editing the codes. This will also avoid errors in coding and instead of so many lines of code, the entry becomes just two lines from 10 and would elongate if more roles are added:

library(readxl)
cv <- read_excel("filename.xlsx")

**Comment by AntoineSoetewey** [comment]
Thank you very much for this suggestion, I didn't think about it but you are completely right.
I edited the article with your remark.
