### ISSUE TITLE
ggplot2 tutorial

### ISSUE THREAD

**Issue by therneau** [AntoineSoetewey/statsandr#10]
That is a nice tutorial on ggplot2.  A minor update is that the first paragraph should probably mention lattice.  Yes, it has been effectively superseded by ggplot2, but it still exists and did play an important role.  

Terry Therneau
Mayo Clinic

**Comment by AntoineSoetewey** [comment]
Dear Terry,

You are totally right, thanks for your suggestion. The article has been improved accordingly (see the [introduction](https://www.statsandr.com/blog/graphics-in-r-with-ggplot2/#introduction)).

Regards,
Antoine
