### ISSUE TITLE
Typo on normal distribution article

### ISSUE THREAD

**Issue by Sercho11** [AntoineSoetewey/statsandr#2]
Hi Antoine, nice article about normal distribution, I found a small typo at the economics and statistics example, it says 11 and should be 8, the standard deviation:

[https://www.statsandr.com/blog/do-my-data-follow-a-normal-distribution-a-note-on-the-most-widely-used-distribution-and-how-to-test-for-normality-in-r/](url)

![image](https://user-images.githubusercontent.com/39209119/73576094-489b7f00-443f-11ea-9601-d7446d49f5ce.png)

**Comment by AntoineSoetewey** [comment]
Nice catch! Thanks for letting me know. The typo has been corrected.
