### ISSUE TITLE
Error: object 'death' not found

### ISSUE THREAD

**Issue by exclusivemekus** [AntoineSoetewey/statsandr#3]
Hi There!
Thank you very much for your tutorial.
I am unable to replicate your code/results 
I get the following message: "Error: object 'death' not found"  after running the following code segment:

`%>%` <- magrittr::`%>%`
# extract the cumulative incidence
df <- coronavirus %>%
  dplyr::filter(Country.Region == "Belgium") %>%
  dplyr::group_by(date, type) %>%
  dplyr::summarise(total = sum(cases, na.rm = TRUE)) %>%
  tidyr::pivot_wider(
    names_from = type,
    values_from = total
  ) %>%
  dplyr::arrange(date) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(active = confirmed - death - recovered) %>%
  dplyr::mutate(
    confirmed_cum = cumsum(confirmed),
    death_cum = cumsum(death),
    recovered_cum = cumsum(recovered),
    active_cum = cumsum(active)
  )

I am sure I am doing the right thing and also have relevant packages loaded.
Please check.
Thanks,
Emmy

**Comment by AntoineSoetewey** [comment]
Hi Emmy,

I just tried on my side and it worked.

So are you sure the `{coronavirus}` package is properly installed and loaded? To check this, do you see the dataset when you run `View(coronavirus)`?

* If you don't see it, it means the package has not been installed and loaded properly. For some unknown reasons, sometimes when installing packages from Github it fails to install some of the dependencies packages. One way to solve it is to install separately those packages and then reinstall the `{coronavirus}` package from Github. Alternatively, you can also dismiss the updates for the dependencies packages when installing the `{coronavirus}` package.
* If you see the dataset, can you see any death cases in the variable `type` for the country you are trying to build the dashboard?

Let me know if this helps.

Best,
Antoine

**Comment by exclusivemekus** [comment]
Hi Antoine,

Thank you very much for your quick response.

I did everything you advised, yet unable to get it to work directly from the embedded dataset.
I went directly to the data source to download the dataset; it worked that way.

Thank you very much again.

I will be glad to see you do the advanced analysis you mentioned at the end of the text.

Cheers!

Emmy

**Comment by AntoineSoetewey** [comment]
Glad you fixed it!
I'll try to write another blog post with more advanced analyses.
Best,
Antoine
