### ISSUE TITLE
cumulative_incident_cases

### ISSUE THREAD

**Issue by tta7592** [AntoineSoetewey/statsandr#4]
Dear Antoine,

thank you very much for you paper on the top resources for covid 19 analytics.

I tried to adjust your code for Belgium for Ukraine. It looks easy - thanks for this. But as I could see - column "cumulative_incident_cases" in my table "fit" is the same as the colum "I"

Should they be equal?

**Comment by AntoineSoetewey** [comment]
Thanks for pointing this out.

No they should not be equal. I corrected the code, see the .Rmd file of this commit: https://github.com/AntoineSoetewey/statsandr/commit/88ffeaa90c901b715c63171a8d68b087ae4853d2.

Let me know if this helps.
Best,
Antoine

**Comment by tta7592** [comment]
Thanks a lot!

One more question, if I may

At the moment I have "cumulative_incident_cases"  for the observed period. But for the predicted period I have NAs for "cumulative_incident_cases" both in the table fir and in the table fitted_cummulative_incidence. Could you, please help. How to get "cumulative_incident_cases" for the predicted period.

Thank you

**Comment by AntoineSoetewey** [comment]
* The table fit and the table fitted_cummulative_incidence are the same, so it's normal you have the same results.
* cumulative_incident_cases are the **observed** cases, so it's normal that we have NAs for the predicted period.
* the column I in the fit table gives you the number of infected people predicted by the model

Does that help you?
