### ISSUE TITLE
Consider replacing utterances with giscus

### ISSUE THREAD

**Issue by laymonage** [AntoineSoetewey/statsandr#51]
Hey there,

I see that you're using utterances for comments. As we know, it utilizes GitHub Issues, which (given enough time) would flood your repository's issues with comments. (Looks like you've already got quite a lot of issues for comments here).

I've been developing an alternative: [giscus](https://giscus.vercel.app), a similar project that utilizes GitHub Discussions instead. It has support for replies and other cool stuff from GitHub Discussions. The big advantage is the fact that it uses your repository's Discussions, which is more suitable for comments. I would really appreciate it if you tried it. Feedback is welcome, the code is [open source](https://github.com/laymonage/giscus).

You can convert existing issues into discussions, as described [here](https://docs.github.com/en/discussions/managing-discussions-for-your-community/moderating-discussions#converting-an-issue-to-a-discussion).

Thanks!

**Comment by AntoineSoetewey** [comment]
Hello @laymonage,

Thanks for your input and for building giscus!

I finally managed to keep things organized by closing the issues that were in fact comments, so I am currently satisfied with utterances. However, I'll make sure to try giscus as soon as I find some time to implement it.

Do you expect to work on it in the long run? I would like to avoid switching back to utterances if you happen to stop working on it.

Regards,
Antoine

**Comment by laymonage** [comment]
@AntoineSoetewey Yup, I'm using it on my personal website and I do intend to keep working on it. GitHub is still actively developing Discussions and there are new features that have yet to be included in the API, which I'm looking forward to bring into giscus.

Thanks for the consideration!

**Comment by AntoineSoetewey** [comment]
Perfect! I'll implement it in a few days and I'll let you know.

Thanks again for building it.

**Comment by AntoineSoetewey** [comment]
Dear @laymonage,

I'm considering switching to giscus by the end of the week.

Can you just confirm that this [issue](https://github.com/utterance/utterances/issues/536) with utterances does not impact giscus?

Thanks in advance!

**Comment by laymonage** [comment]
@AntoineSoetewey I can confirm you it does not. Utterances uses the @utterances-bot account to create new issues, which is a personal account, for reasons I do not know why. Meanwhile, giscus uses the app's credentials, meaning that new issues will be created as the app. It will have an official [bot] tag from GitHub. Example: https://github.com/laymonage/giscus/discussions/62

**Comment by AntoineSoetewey** [comment]
Thank you!

**Comment by AntoineSoetewey** [comment]
Hello @laymonage,

I switched to giscus.

Do you know how I can fix the width? https://statsandr.com/blog/variable-types-and-examples/

**Comment by AntoineSoetewey** [comment]
Never mind, I found the solution in https://github.com/laymonage/giscus/issues/90.
